// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using System.Reflection;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.InheritedClassPrivateSetters;

public class CreatePerson :
    CreatePerson.ICreatePerson,
    CreatePerson.IWithName,
    CreatePerson.IOfAgeBornOn
{
    private readonly Person person;
    private static readonly PropertyInfo namePropertyInfo;
    private static readonly PropertyInfo agePropertyInfo;
    private static readonly MethodInfo bornOnMethodInfo;

    static CreatePerson()
    {
        namePropertyInfo = typeof(Person).GetProperty("Name", BindingFlags.Instance | BindingFlags.Public)!;
        agePropertyInfo = typeof(Person).GetProperty("Age", BindingFlags.Instance | BindingFlags.Public)!;
        bornOnMethodInfo = typeof(Person).GetMethod(
            "BornOn",
            0,
            BindingFlags.Instance | BindingFlags.NonPublic,
            null,
            new Type[] { typeof(System.DateOnly) },
            null)!;
    }

    private CreatePerson()
    {
        person = new Person();
    }

    public static ICreatePerson InitialStep()
    {
        return new CreatePerson();
    }

    public static IOfAgeBornOn WithName(string name)
    {
        CreatePerson createPerson = new CreatePerson();
        CreatePerson.namePropertyInfo.SetValue(createPerson.person, name);
        return createPerson;
    }

    IOfAgeBornOn IWithName.WithName(string name)
    {
        CreatePerson.namePropertyInfo.SetValue(person, name);
        return this;
    }

    Person IOfAgeBornOn.OfAge(int age)
    {
        CreatePerson.agePropertyInfo.SetValue(person, age);
        return person;
    }

    Person IOfAgeBornOn.BornOn(System.DateOnly dateOfBirth)
    {
        CreatePerson.bornOnMethodInfo.Invoke(person, new object?[] { dateOfBirth });
        return person;
    }

    public interface ICreatePerson : IWithName
    {
    }

    public interface IWithName
    {
        IOfAgeBornOn WithName(string name);
    }

    public interface IOfAgeBornOn
    {
        Person OfAge(int age);

        Person BornOn(System.DateOnly dateOfBirth);
    }
}