// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.InheritedClassPrivateSetters;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName,
    CreateStudent.IOfAgeBornOn,
    CreateStudent.IInSemester
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IOfAgeBornOn WithName(string name)
    {
        CreateStudent createStudent = new CreateStudent();
        SetName(createStudent.student, name);
        return createStudent;
    }

    IOfAgeBornOn IWithName.WithName(string name)
    {
        SetName(student, name);
        return this;
    }

    IInSemester IOfAgeBornOn.OfAge(int age)
    {
        SetAge(student, age);
        return this;
    }

    IInSemester IOfAgeBornOn.BornOn(System.DateOnly dateOfBirth)
    {
        CallBornOn(student, dateOfBirth);
        return this;
    }

    Student IInSemester.InSemester(int semester)
    {
        SetSemester(student, semester);
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        IOfAgeBornOn WithName(string name);
    }

    public interface IOfAgeBornOn
    {
        IInSemester OfAge(int age);

        IInSemester BornOn(System.DateOnly dateOfBirth);
    }

    public interface IInSemester
    {
        Student InSemester(int semester);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Semester")]
    private static extern void SetSemester(Student student, int value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    private static extern void SetName(Person person, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Age")]
    private static extern void SetAge(Person person, int value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "BornOn")]
    private static extern void CallBornOn(Person person, System.DateOnly dateOfBirth);
}