// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.InheritedClassPrivateSetters;

public class CreatePerson :
    CreatePerson.ICreatePerson,
    CreatePerson.IWithName,
    CreatePerson.IOfAgeBornOn
{
    private readonly Person person;

    private CreatePerson()
    {
        person = new Person();
    }

    public static ICreatePerson InitialStep()
    {
        return new CreatePerson();
    }

    public static IOfAgeBornOn WithName(string name)
    {
        CreatePerson createPerson = new CreatePerson();
        SetName(createPerson.person, name);
        return createPerson;
    }

    IOfAgeBornOn IWithName.WithName(string name)
    {
        SetName(person, name);
        return this;
    }

    Person IOfAgeBornOn.OfAge(int age)
    {
        SetAge(person, age);
        return person;
    }

    Person IOfAgeBornOn.BornOn(System.DateOnly dateOfBirth)
    {
        CallBornOn(person, dateOfBirth);
        return person;
    }

    public interface ICreatePerson : IWithName
    {
    }

    public interface IWithName
    {
        IOfAgeBornOn WithName(string name);
    }

    public interface IOfAgeBornOn
    {
        Person OfAge(int age);

        Person BornOn(System.DateOnly dateOfBirth);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    private static extern void SetName(Person person, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Age")]
    private static extern void SetAge(Person person, int value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "BornOn")]
    private static extern void CallBornOn(Person person, System.DateOnly dateOfBirth);
}