// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using M31.FluentApi.Attributes;
using System;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithDetails
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static Student WithDetails(string createAddress, M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.Address address)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.CreateAddress = createAddress;
        createStudent.student.Address = address;
        return createStudent.student;
    }

    public static Student WithDetails(string createAddress, Func<M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.CreateAddress.ICreateAddress, M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.Address> createAddress)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.CreateAddress = createAddress;
        createStudent.student.Address = createAddress(M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.CreateAddress.InitialStep());
        return createStudent.student;
    }

    Student IWithDetails.WithDetails(string createAddress, M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.Address address)
    {
        student.CreateAddress = createAddress;
        student.Address = address;
        return student;
    }

    Student IWithDetails.WithDetails(string createAddress, Func<M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.CreateAddress.ICreateAddress, M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.Address> createAddress)
    {
        student.CreateAddress = createAddress;
        student.Address = createAddress(M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.CreateAddress.InitialStep());
        return student;
    }

    public interface ICreateStudent : IWithDetails
    {
    }

    public interface IWithDetails
    {
        Student WithDetails(string createAddress, M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.Address address);

        Student WithDetails(string createAddress, Func<M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.CreateAddress.ICreateAddress, M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass3.Address> createAddress);
    }
}