// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.InheritedClassProtectedMembers;

public class CreatePerson :
    CreatePerson.ICreatePerson,
    CreatePerson.IWithName,
    CreatePerson.IBornOn
{
    private readonly Person person;

    private CreatePerson()
    {
        person = new Person();
    }

    public static ICreatePerson InitialStep()
    {
        return new CreatePerson();
    }

    public static IBornOn WithName(string name)
    {
        CreatePerson createPerson = new CreatePerson();
        SetName(createPerson.person, name!);
        return createPerson;
    }

    IBornOn IWithName.WithName(string name)
    {
        SetName(person, name!);
        return this;
    }

    Person IBornOn.BornOn(System.DateOnly dateOfBirth)
    {
        SetDateOfBirth(person, dateOfBirth!);
        return person;
    }

    public interface ICreatePerson : IWithName
    {
    }

    public interface IWithName
    {
        IBornOn WithName(string name);
    }

    public interface IBornOn
    {
        Person BornOn(System.DateOnly dateOfBirth);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    private static extern void SetName(Person person, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_DateOfBirth")]
    private static extern void SetDateOfBirth(Person person, System.DateOnly value);
}