// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.GetPrivateSetPropertyClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.ICreateStudentFromExisting,
    CreateStudent.IInSemester
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    private CreateStudent(Student student)
    {
        this.student = student;
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static ICreateStudentFromExisting FromExisting(Student student)
    {
        return new CreateStudent(student);
    }

    public static Student InSemester(int semester)
    {
        CreateStudent createStudent = new CreateStudent();
        SetSemester(createStudent.student, semester!);
        return createStudent.student;
    }

    Student IInSemester.InSemester(int semester)
    {
        SetSemester(student, semester!);
        return student;
    }

    public interface ICreateStudent : IInSemester
    {
    }

    public interface ICreateStudentFromExisting : IInSemester
    {
    }

    public interface IInSemester
    {
        Student InSemester(int semester);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Semester")]
    private static extern void SetSemester(Student student, int value);
}