// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Collections.Generic;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.CollectionMemberClassWithSuppression;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWhoseFriendsAre,
    CreateStudent.IWithPets,
    CreateStudent.IWithBackpackContent
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithPets WhoseFriendsAre(System.Collections.Generic.List<string> friends)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Friends = friends;
        return createStudent;
    }

    public static IWithPets WhoseFriendsAre(params string[] friends)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Friends = new List<string>(friends);
        return createStudent;
    }

    IWithPets IWhoseFriendsAre.WhoseFriendsAre(System.Collections.Generic.List<string> friends)
    {
        student.Friends = friends;
        return this;
    }

    IWithPets IWhoseFriendsAre.WhoseFriendsAre(params string[] friends)
    {
        student.Friends = new List<string>(friends);
        return this;
    }

    IWithBackpackContent IWithPets.WithPets(params string[] pets)
    {
        student.Pets = pets;
        return this;
    }

    Student IWithBackpackContent.WithBackpackContent(System.Collections.Generic.HashSet<string> backpackContent)
    {
        student.BackpackContent = backpackContent;
        return student;
    }

    Student IWithBackpackContent.WithBackpackContent(params string[] backpackContent)
    {
        student.BackpackContent = new HashSet<string>(backpackContent);
        return student;
    }

    public interface ICreateStudent : IWhoseFriendsAre
    {
    }

    public interface IWhoseFriendsAre
    {
        IWithPets WhoseFriendsAre(System.Collections.Generic.List<string> friends);

        IWithPets WhoseFriendsAre(params string[] friends);
    }

    public interface IWithPets
    {
        IWithBackpackContent WithPets(params string[] pets);
    }

    public interface IWithBackpackContent
    {
        Student WithBackpackContent(System.Collections.Generic.HashSet<string> backpackContent);

        Student WithBackpackContent(params string[] backpackContent);
    }
}