// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentApiComments.CommentedPropertiesClassAdvanced;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName,
    CreateStudent.IOfAge,
    CreateStudent.ILivingIn,
    CreateStudent.IWhoIsHappy
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IOfAge WithName(string name)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Name = name;
        return createStudent;
    }

    IOfAge IWithName.WithName(string name)
    {
        student.Name = name;
        return this;
    }

    /// <inheritdoc/>
    ILivingIn IOfAge.OfAge(int age)
    {
        student.Age = age;
        return this;
    }

    /// <inheritdoc/>
    IWhoIsHappy ILivingIn.LivingIn(string? city)
    {
        student.City = city;
        return this;
    }

    /// <inheritdoc/>
    IWhoIsHappy ILivingIn.LivingInBoston()
    {
        return this;
    }

    /// <inheritdoc/>
    IWhoIsHappy ILivingIn.InUnknownCity()
    {
        student.City = null;
        return this;
    }

    Student IWhoIsHappy.WhoIsHappy(bool? isHappy)
    {
        SetIsHappy(student, isHappy!);
        return student;
    }

    Student IWhoIsHappy.WhoIsSad()
    {
        SetIsHappy(student, false!);
        return student;
    }

    Student IWhoIsHappy.WithUnknownMood()
    {
        SetIsHappy(student, null!);
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        IOfAge WithName(string name);
    }

    public interface IOfAge
    {
        /// <summary>Sets the students's age.</summary>
        /// <param name="age">The student's age.</param>
        ILivingIn OfAge(int age);
    }

    public interface ILivingIn
    {
        /// <summary>Sets the student's city.</summary>
        /// <param name="city">The student's city.</param>
        IWhoIsHappy LivingIn(string? city);

        /// <summary>Set's the student's city to Boston.</summary>
        IWhoIsHappy LivingInBoston();

        /// <summary>Set's the student's city to null.</summary>
        IWhoIsHappy InUnknownCity();
    }

    public interface IWhoIsHappy
    {
        Student WhoIsHappy(bool? isHappy = true);

        Student WhoIsSad();

        Student WithUnknownMood();
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_IsHappy")]
    private static extern void SetIsHappy(Student student, bool? value);
}