using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace M31.FluentApi.Tests.CodeGeneration;

internal class TestDataProvider : IEnumerable<object[]>
{
    private readonly List<object[]> testClasses =
        Filter([],
        [
            ["Abstract", "AliasNamespaceClass", "Student"],
            ["Abstract", "CollectionInterfaceMemberClass", "Student"],
            ["Abstract", "CollectionMemberClass", "Student"],
            ["Abstract", "CollectionMemberClassWithSuppression", "Student"],
            ["Abstract", "CollectionNullableArrayClass", "Student"],
            ["Abstract", "ContinueWithAfterCompoundClass", "Student"],
            ["Abstract", "ContinueWithInForkClass", "Student"],
            ["Abstract", "ContinueWithOfOverloadedMethodClass", "Student"],
            ["Abstract", "ContinueWithSelfClass", "Student"],
            ["Abstract", "CustomFluentMethodNameClass", "Student"],
            ["Abstract", "DefaultFluentMethodNameClass", "Student"],
            ["Abstract", "FluentApiComments", "CommentedCompoundClass", "Student"],
            ["Abstract", "FluentApiComments", "CommentedLambdaCollectionClass", "Student|Phone"],
            ["Abstract", "FluentApiComments", "CommentedMethodsClass", "Student"],
            ["Abstract", "FluentApiComments", "CommentedPropertiesClass", "Student"],
            ["Abstract", "FluentApiComments", "CommentedPropertiesClassAdvanced", "Student"],
            ["Abstract", "FluentApiComments", "IncompletelyCommentedPropertyClass", "Student"],
            ["Abstract", "FluentApiComments", "RedundantCommentCompoundClass", "Student"],
            ["Abstract", "FluentApiComments", "WronglyCommentedClass", "Student"],
            ["Abstract", "FluentApiComments", "WronglyCommentedClass2", "Student"],
            ["Abstract", "EmptyClass", "Student"],
            ["Abstract", "FluentDefaultMemberClass", "Student"],
            ["Abstract", "FluentLambdaClass", "Student|Address"],
            ["Abstract", "FluentLambdaClassInDifferentNamespace", "Student|Address"],
            ["Abstract", "FluentLambdaCollectionClass", "Student|Address"],
            ["Abstract", "FluentLambdaCompoundClass", "Student|Address|Phone"],
            ["Abstract", "FluentLambdaCompoundOfSameTypeClass", "Student|Address"],
            ["Abstract", "FluentLambdaManyCollectionsClass", "Student|Address"],
            ["Abstract", "FluentLambdaManyPrivateCollectionsClass", "Student|Address"],
            ["Abstract", "FluentLambdaNullablePropertyClass", "Student|Address"],
            ["Abstract", "FluentLambdaRecursiveClass", "Student"],
            ["Abstract", "FluentLambdaSingleStepClass", "Student|Address"],
            ["Abstract", "FluentMethodClass", "Student"],
            ["Abstract", "FluentMethodDefaultValuesClass", "Student"],
            ["Abstract", "FluentMethodParameterModifiersClass", "Student"],
            ["Abstract", "FluentNullableClass", "Student"],
            ["Abstract", "FluentNullableNoNullableAnnotationClass", "Student"],
            ["Abstract", "FluentNullableNoNullableAnnotationPrivateSetClass", "Student"],
            ["Abstract", "FluentReturnMultiStepClass", "Student"],
            ["Abstract", "FluentReturnMultiStepPrivateMethodsClass", "Student"],
            ["Abstract", "FluentReturnSingleStepClass", "Student"],
            ["Abstract", "FluentReturnSingleStepPrivateMethodsClass", "Student"],
            ["Abstract", "ForkClass", "Student"],
            ["Abstract", "FullyQualifiedTypeClass", "Student"],
            ["Abstract", "GenericClass", "Student"],
            ["Abstract", "GenericClassPrivateConstructor", "Student"],
            ["Abstract", "GenericClassPrivateDefaultConstructor", "Student"],
            ["Abstract", "GenericClassWithConstraints", "Student"],
            ["Abstract", "GenericClassWithGenericMethods", "Student"],
            ["Abstract", "GenericClassWithPrivateGenericMethods", "Student"],
            ["Abstract", "GenericMethodWithConstraintsClass", "Student"],
            ["Abstract", "GenericOverloadedMethodClass", "Student"],
            ["Abstract", "GenericOverloadedPrivateMethodClass", "Student"],
            ["Abstract", "GetInitPropertyClass", "Student"],
            ["Abstract", "GetPrivateInitPropertyClass", "Student"],
            ["Abstract", "GetPrivateSetPropertyClass", "Student"],
            ["Abstract", "InternalPropertyClass", "Student"],
            ["Abstract", "InheritedClass", "Student|Person"],
            ["Abstract", "InheritedClassPrivateSetters", "Student|Person"],
            ["Abstract", "InheritedClassProtectedMembers", "Student|Person"],
            ["Abstract", "InheritedClassProtectedSetters", "Student|Person"],
            ["Abstract", "InheritedRecord", "Student|Person"],
            ["Abstract", "InternalClass", "Student"],
            ["Abstract", "KeywordClass", "Student"],
            ["Abstract", "NonGenericCollectionMemberClass", "Student"],
            ["Abstract", "NullablePredicateAndCollectionClass", "Student"],
            ["Abstract", "OneMemberClass", "Student"],
            ["Abstract", "OverloadedMethodClass", "Student"],
            ["Abstract", "ParameterAnnotationsPrivateConstructorClass", "Student"],
            ["Abstract", "ParameterAnnotationsPublicConstructorClass", "Student"],
            ["Abstract", "PartialClass", "Student1|Student2"],
            ["Abstract", "PredicateClass", "Student"],
            ["Abstract", "PredicatePrivateFieldClass", "Student"],
            ["Abstract", "PrivateConstructorClass", "Student"],
            ["Abstract", "PrivateFieldClass", "Student"],
            ["Abstract", "PrivateFluentMethodClass", "Student"],
            ["Abstract", "PrivateFluentMethodNullableParameterClass", "Student"],
            ["Abstract", "PrivateFluentMethodParameterModifiersClass", "Student"],
            ["Abstract", "PrivateReadonlyFieldClass", "Student"],
            ["Abstract", "PrivateUnderscoreFieldClass", "Student"],
            ["Abstract", "PublicFieldClass", "Student"],
            ["Abstract", "PublicReadonlyFieldClass", "Student"],
            ["Abstract", "SameNameMemberClass", "Student"],
            ["Abstract", "SkippableFirstMemberClass", "Student"],
            ["Abstract", "SkippableFirstTwoMembersClass", "Student"],
            ["Abstract", "SkippableForkMembersClass", "Student"],
            ["Abstract", "SkippableLoopClass", "Student"],
            ["Abstract", "SkippableMemberClass", "Student"],
            ["Abstract", "SkippableSeveralMembersClass", "Student"],
            ["Abstract", "SkippableTwoLoopsClass", "Student"],
            ["Abstract", "ThreeMemberClass", "Student"],
            ["Abstract", "ThreeMemberRecord", "Student"],
            ["Abstract", "ThreeMemberRecordPrimaryConstructor", "Student"],
            ["Abstract", "ThreeMemberStruct", "Student"],
            ["Abstract", "ThreePrivateMembersClass", "Student"],
            ["Abstract", "ThreeMemberRecordStruct", "Student"],
            ["Abstract", "TryBreakFluentApiClass1", "Student"],
            ["Abstract", "TryBreakFluentApiClass2", "Student"],
            ["Abstract", "TryBreakFluentApiClass3", "Student|Address"],
            ["Abstract", "TwoMemberClass", "Student"],
            ["Abstract", "TwoParameterCompoundClass", "Student"],
            ["Abstract", "TwoParameterCompoundClassReversedParameters", "Student"],
            ["DocumentedStudentClass", "DocumentedStudent"],
            ["PersonClass", "Person"],
            ["StudentClass", "Student"]
        ]).Select(l => new string[] { "..", "..", "..", "CodeGeneration", "TestClasses" }
            .Concat(l).Reverse().ToArray()).ToList(); // reversed for better readability in the unit test panel

    public IEnumerator<object[]> GetEnumerator() => testClasses.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    private static List<object[]> Filter(string[] testsToFilter, List<object[]> tests)
    {
        return testsToFilter.Length == 0 ? tests : tests.Where(t => testsToFilter.Contains((string)t[^2])).ToList();
    }
}