// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using M31.FluentApi.Attributes;
using System.Reflection;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.InheritedClassProtectedSetters;

public class CreatePerson :
    CreatePerson.ICreatePerson,
    CreatePerson.IInSemester
{
    private readonly Person person;
    private static readonly PropertyInfo semesterPropertyInfo;

    static CreatePerson()
    {
        semesterPropertyInfo = typeof(Person).GetProperty("Semester", BindingFlags.Instance | BindingFlags.Public)!;
    }

    private CreatePerson()
    {
        person = new Person();
    }

    public static ICreatePerson InitialStep()
    {
        return new CreatePerson();
    }

    public static Person InSemester(int semester)
    {
        CreatePerson createPerson = new CreatePerson();
        CreatePerson.semesterPropertyInfo.SetValue(createPerson.person, semester);
        return createPerson.person;
    }

    Person IInSemester.InSemester(int semester)
    {
        CreatePerson.semesterPropertyInfo.SetValue(person, semester);
        return person;
    }

    public interface ICreatePerson : IInSemester
    {
    }

    public interface IInSemester
    {
        Person InSemester(int semester);
    }
}