// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentReturnMultiStepPrivateMethodsClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName,
    CreateStudent.IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter WithName(string name)
    {
        CreateStudent createStudent = new CreateStudent();
        SetName(createStudent.student, name!);
        return createStudent;
    }

    IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter IWithName.WithName(string name)
    {
        SetName(student, name!);
        return this;
    }

    void IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnVoidMethod()
    {
        CallReturnVoidMethod(student);
    }

    int IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnIntMethod()
    {
        return CallReturnIntMethod(student);
    }

    System.Collections.Generic.List<int> IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnListMethod()
    {
        return CallReturnListMethod(student);
    }

    int IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnIntMethodWithRefParameter(ref string s)
    {
        return CallReturnIntMethodWithRefParameter(student, ref s);
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter WithName(string name);
    }

    public interface IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter
    {
        void ReturnVoidMethod();

        int ReturnIntMethod();

        System.Collections.Generic.List<int> ReturnListMethod();

        int ReturnIntMethodWithRefParameter(ref string s);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    private static extern void SetName(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "ReturnVoidMethod")]
    private static extern void CallReturnVoidMethod(Student student);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "ReturnIntMethod")]
    private static extern int CallReturnIntMethod(Student student);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "ReturnListMethod")]
    private static extern System.Collections.Generic.List<int> CallReturnListMethod(Student student);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "ReturnIntMethodWithRefParameter")]
    private static extern int CallReturnIntMethodWithRefParameter(Student student, ref string s);
}