// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.OverloadedMethodClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.INamedNamed
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static Student Named(string firstName, string lastName)
    {
        CreateStudent createStudent = new CreateStudent();
        CallNamed(createStudent.student, firstName, lastName);
        return createStudent.student;
    }

    public static Student Named(string lastName)
    {
        CreateStudent createStudent = new CreateStudent();
        CallNamed(createStudent.student, lastName);
        return createStudent.student;
    }

    Student INamedNamed.Named(string firstName, string lastName)
    {
        CallNamed(student, firstName, lastName);
        return student;
    }

    Student INamedNamed.Named(string lastName)
    {
        CallNamed(student, lastName);
        return student;
    }

    public interface ICreateStudent : INamedNamed
    {
    }

    public interface INamedNamed
    {
        Student Named(string firstName, string lastName);

        Student Named(string lastName);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "Named")]
    private static extern void CallNamed(Student student, string firstName, string lastName);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "Named")]
    private static extern void CallNamed(Student student, string lastName);
}