// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.DocumentationComments.RedundantCommentCompoundClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    /// <summary>Sets the student's name.</summary>
    /// <param name="firstName">The student's first name.</param>
    /// <param name="lastName">The student's last name.</param>
    /// <summary>Sets the student's name.</summary>
    /// <param name="firstName">The student's first name.</param>
    /// <param name="lastName">The student's last name.</param>
    public static Student WithName(string firstName, string lastName)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.FirstName = firstName;
        createStudent.student.LastName = lastName;
        return createStudent.student;
    }

    /// <inheritdoc/>
    Student IWithName.WithName(string firstName, string lastName)
    {
        student.FirstName = firstName;
        student.LastName = lastName;
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        /// <summary>Sets the student's name.</summary>
        /// <param name="firstName">The student's first name.</param>
        /// <param name="lastName">The student's last name.</param>
        /// <summary>Sets the student's name.</summary>
        /// <param name="firstName">The student's first name.</param>
        /// <param name="lastName">The student's last name.</param>
        Student WithName(string firstName, string lastName);
    }
}