// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Collections.Generic;
using M31.FluentApi.Attributes;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentReturnSingleStepClass;

public class CreateStudent
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static void ReturnVoid()
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.ReturnVoid();
    }

    public static int ReturnInt()
    {
        CreateStudent createStudent = new CreateStudent();
        return createStudent.student.ReturnInt();
    }

    public static System.Collections.Generic.List<int> ReturnList()
    {
        CreateStudent createStudent = new CreateStudent();
        return createStudent.student.ReturnList();
    }
}