// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#nullable enable

using M31.FluentApi.Attributes;
using System.Reflection;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.CollectionNullableArrayClass;

public class CreateStudent
{
    private readonly Student student;
    private static readonly PropertyInfo friendsPropertyInfo;

    static CreateStudent()
    {
        friendsPropertyInfo = typeof(Student).GetProperty("Friends", BindingFlags.Instance | BindingFlags.Public)!;
    }

    private CreateStudent()
    {
        student = new Student();
    }

    public static Student WhoseFriendsAre(params string[]? friends)
    {
        CreateStudent createStudent = new CreateStudent();
        friendsPropertyInfo.SetValue(createStudent.student, friends);
        return createStudent.student;
    }

    public static Student WhoseFriendIs(string friend)
    {
        CreateStudent createStudent = new CreateStudent();
        friendsPropertyInfo.SetValue(createStudent.student, new string[1]{ friend });
        return createStudent.student;
    }

    public static Student WhoHasNoFriends()
    {
        CreateStudent createStudent = new CreateStudent();
        friendsPropertyInfo.SetValue(createStudent.student, new string[0]);
        return createStudent.student;
    }
}