// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.TryBreakFluentApiClass2;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.ISomeMethod
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static Student SomeMethod(string createStudent)
    {
        CreateStudent createStudent2 = new CreateStudent();
        CallSomeMethod(createStudent2.student, createStudent);
        return createStudent2.student;
    }

    Student ISomeMethod.SomeMethod(string createStudent)
    {
        CallSomeMethod(student, createStudent);
        return student;
    }

    public interface ICreateStudent : ISomeMethod
    {
    }

    public interface ISomeMethod
    {
        Student SomeMethod(string createStudent);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "SomeMethod")]
    private static extern void CallSomeMethod(Student student, string createStudent);
}