// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.PartialClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithFirstName,
    CreateStudent.IWithLastName
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithLastName WithFirstName(string firstName)
    {
        CreateStudent createStudent = new CreateStudent();
        SetFirstName(createStudent.student, firstName!);
        return createStudent;
    }

    IWithLastName IWithFirstName.WithFirstName(string firstName)
    {
        SetFirstName(student, firstName!);
        return this;
    }

    Student IWithLastName.WithLastName(string lastName)
    {
        SetLastName(student, lastName!);
        return student;
    }

    public interface ICreateStudent : IWithFirstName
    {
    }

    public interface IWithFirstName
    {
        IWithLastName WithFirstName(string firstName);
    }

    public interface IWithLastName
    {
        Student WithLastName(string lastName);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_FirstName")]
    private static extern void SetFirstName(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_LastName")]
    private static extern void SetLastName(Student student, string value);
}