// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentApiComments.CommentedCompoundClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName,
    CreateStudent.IStudies
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    /// <summary>Sets the student's name.</summary>
    /// <param name="firstName">The student's first name.</param>
    /// <param name="lastName">The student's last name.</param>
    public static IStudies WithName(string firstName, string lastName)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.FirstName = firstName;
        createStudent.student.LastName = lastName;
        return createStudent;
    }

    /// <inheritdoc/>
    IStudies IWithName.WithName(string firstName, string lastName)
    {
        student.FirstName = firstName;
        student.LastName = lastName;
        return this;
    }

    /// <inheritdoc/>
    Student IStudies.Studies(string courseOfStudy, int semester)
    {
        student.CourseOfStudy = courseOfStudy;
        student.Semester = semester;
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        /// <summary>Sets the student's name.</summary>
        /// <param name="firstName">The student's first name.</param>
        /// <param name="lastName">The student's last name.</param>
        IStudies WithName(string firstName, string lastName);
    }

    public interface IStudies
    {
        /// <summary>Sets the student's course of study and current semester.</summary>
        /// <param name="courseOfStudy">The student's course of study.</param>
        /// <param name="semester">The student's current semester.</param>
        Student Studies(string courseOfStudy, int semester);
    }
}