// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentApiComments.WronglyCommentedClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.ICreateStudentFromExisting,
    CreateStudent.IWithName
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    private CreateStudent(Student student)
    {
        this.student = student;
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static ICreateStudentFromExisting FromExisting(Student student)
    {
        return new CreateStudent(student);
    }

    public static Student WithName(string name)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Name = name;
        return createStudent.student;
    }

    Student IWithName.WithName(string name)
    {
        student.Name = name;
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface ICreateStudentFromExisting : IWithName
    {
    }

    public interface IWithName
    {
        Student WithName(string name);
    }
}