// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.ParameterAnnotationsPrivateConstructorClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithProperty1,
    CreateStudent.IWithProperty2
{
    private readonly Student student;

    private CreateStudent()
    {
        string v = default!;
        int v2 = default!;
        student = CreateStudentInstance(ref v, in v2, out _);
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithProperty2 WithProperty1(string property1)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Property1 = property1;
        return createStudent;
    }

    IWithProperty2 IWithProperty1.WithProperty1(string property1)
    {
        student.Property1 = property1;
        return this;
    }

    Student IWithProperty2.WithProperty2(int property2)
    {
        student.Property2 = property2;
        return student;
    }

    public interface ICreateStudent : IWithProperty1
    {
    }

    public interface IWithProperty1
    {
        IWithProperty2 WithProperty1(string property1);
    }

    public interface IWithProperty2
    {
        Student WithProperty2(int property2);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    private static extern Student CreateStudentInstance(ref string property1, in int property2, out double outValue);
}