// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using M31.FluentApi.Attributes;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentLambdaCompoundClass;

public class CreatePhone :
    CreatePhone.ICreatePhone,
    CreatePhone.IWithNumber,
    CreatePhone.IWithUsage
{
    private readonly Phone phone;

    private CreatePhone()
    {
        phone = new Phone();
    }

    public static ICreatePhone InitialStep()
    {
        return new CreatePhone();
    }

    public static IWithUsage WithNumber(string number)
    {
        CreatePhone createPhone = new CreatePhone();
        createPhone.phone.Number = number;
        return createPhone;
    }

    IWithUsage IWithNumber.WithNumber(string number)
    {
        phone.Number = number;
        return this;
    }

    Phone IWithUsage.WithUsage(string usage)
    {
        phone.Usage = usage;
        return phone;
    }

    public interface ICreatePhone : IWithNumber
    {
    }

    public interface IWithNumber
    {
        IWithUsage WithNumber(string number);
    }

    public interface IWithUsage
    {
        Phone WithUsage(string usage);
    }
}