// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Collections.Generic;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FullyQualifiedTypeClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IBornOnWithFriends
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static Student BornOn(System.DateOnly dateOfBirth)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.DateOfBirth = dateOfBirth;
        return createStudent.student;
    }

    public static Student WithFriends(System.Collections.Generic.List<string> friends)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Friends = friends;
        return createStudent.student;
    }

    public static Student WithFriends(params string[] friends)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Friends = new List<string>(friends);
        return createStudent.student;
    }

    public static Student WithFriend(string friend)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Friends = new List<string>(1){ friend };
        return createStudent.student;
    }

    public static Student WithZeroFriends()
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Friends = new List<string>(0);
        return createStudent.student;
    }

    Student IBornOnWithFriends.BornOn(System.DateOnly dateOfBirth)
    {
        student.DateOfBirth = dateOfBirth;
        return student;
    }

    Student IBornOnWithFriends.WithFriends(System.Collections.Generic.List<string> friends)
    {
        student.Friends = friends;
        return student;
    }

    Student IBornOnWithFriends.WithFriends(params string[] friends)
    {
        student.Friends = new List<string>(friends);
        return student;
    }

    Student IBornOnWithFriends.WithFriend(string friend)
    {
        student.Friends = new List<string>(1){ friend };
        return student;
    }

    Student IBornOnWithFriends.WithZeroFriends()
    {
        student.Friends = new List<string>(0);
        return student;
    }

    public interface ICreateStudent : IBornOnWithFriends
    {
    }

    public interface IBornOnWithFriends
    {
        Student BornOn(System.DateOnly dateOfBirth);

        Student WithFriends(System.Collections.Generic.List<string> friends);

        Student WithFriends(params string[] friends);

        Student WithFriend(string friend);

        Student WithZeroFriends();
    }
}