// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.PersonClass;

public class CreatePerson :
    CreatePerson.ICreatePerson,
    CreatePerson.IWithFirstName,
    CreatePerson.IWithMiddleName,
    CreatePerson.IWithLastName,
    CreatePerson.IWhoseAddressIsUnknownWhoLivesAtAddressWhoIsADigitalNomad,
    CreatePerson.IWithHouseNumber,
    CreatePerson.IWithStreet,
    CreatePerson.IInCity,
    CreatePerson.ILivingInCity
{
    private readonly Person person;

    private CreatePerson()
    {
        person = new Person();
    }

    public static ICreatePerson InitialStep()
    {
        return new CreatePerson();
    }

    public static IWithMiddleName WithFirstName(string firstName)
    {
        CreatePerson createPerson = new CreatePerson();
        SetFirstName(createPerson.person, firstName!);
        return createPerson;
    }

    IWithMiddleName IWithFirstName.WithFirstName(string firstName)
    {
        SetFirstName(person, firstName!);
        return this;
    }

    IWithLastName IWithMiddleName.WithMiddleName(string? middleName)
    {
        SetMiddleName(person, middleName!);
        return this;
    }

    IWhoseAddressIsUnknownWhoLivesAtAddressWhoIsADigitalNomad IWithLastName.WithLastName(string lastName)
    {
        SetLastName(person, lastName!);
        return this;
    }

    Person IWhoseAddressIsUnknownWhoLivesAtAddressWhoIsADigitalNomad.WhoseAddressIsUnknown()
    {
        CallWhoseAddressIsUnknown(person);
        return person;
    }

    IWithHouseNumber IWhoseAddressIsUnknownWhoLivesAtAddressWhoIsADigitalNomad.WhoLivesAtAddress()
    {
        CallWhoLivesAtAddress(person);
        return this;
    }

    ILivingInCity IWhoseAddressIsUnknownWhoLivesAtAddressWhoIsADigitalNomad.WhoIsADigitalNomad()
    {
        CallWhoIsADigitalNomad(person);
        return this;
    }

    IWithStreet IWithHouseNumber.WithHouseNumber(string houseNumber)
    {
        CallWithHouseNumber(person, houseNumber);
        return this;
    }

    IInCity IWithStreet.WithStreet(string street)
    {
        CallWithStreet(person, street);
        return this;
    }

    Person IInCity.InCity(string city)
    {
        CallInCity(person, city);
        return person;
    }

    Person ILivingInCity.LivingInCity(string city)
    {
        CallLivingInCity(person, city);
        return person;
    }

    public interface ICreatePerson : IWithFirstName
    {
    }

    public interface IWithFirstName
    {
        IWithMiddleName WithFirstName(string firstName);
    }

    public interface IWithMiddleName : IWithLastName
    {
        IWithLastName WithMiddleName(string? middleName);
    }

    public interface IWithLastName
    {
        IWhoseAddressIsUnknownWhoLivesAtAddressWhoIsADigitalNomad WithLastName(string lastName);
    }

    public interface IWhoseAddressIsUnknownWhoLivesAtAddressWhoIsADigitalNomad
    {
        Person WhoseAddressIsUnknown();

        IWithHouseNumber WhoLivesAtAddress();

        ILivingInCity WhoIsADigitalNomad();
    }

    public interface IWithHouseNumber
    {
        IWithStreet WithHouseNumber(string houseNumber);
    }

    public interface IWithStreet
    {
        IInCity WithStreet(string street);
    }

    public interface IInCity
    {
        Person InCity(string city);
    }

    public interface ILivingInCity
    {
        Person LivingInCity(string city);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_FirstName")]
    private static extern void SetFirstName(Person person, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_MiddleName")]
    private static extern void SetMiddleName(Person person, string? value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_LastName")]
    private static extern void SetLastName(Person person, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "WhoseAddressIsUnknown")]
    private static extern void CallWhoseAddressIsUnknown(Person person);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "WhoLivesAtAddress")]
    private static extern void CallWhoLivesAtAddress(Person person);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "WithHouseNumber")]
    private static extern void CallWithHouseNumber(Person person, string houseNumber);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "WithStreet")]
    private static extern void CallWithStreet(Person person, string street);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "InCity")]
    private static extern void CallInCity(Person person, string city);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "WhoIsADigitalNomad")]
    private static extern void CallWhoIsADigitalNomad(Person person);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "LivingInCity")]
    private static extern void CallLivingInCity(Person person, string city);
}