// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.StudentClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.INamed,
    CreateStudent.IOfAgeBornOn,
    CreateStudent.IInSemester,
    CreateStudent.ILivingIn,
    CreateStudent.IWhoIsHappy,
    CreateStudent.IWhoseFriendsAre
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IOfAgeBornOn Named(string firstName, string lastName)
    {
        CreateStudent createStudent = new CreateStudent();
        SetFirstName(createStudent.student, firstName);
        SetLastName(createStudent.student, lastName);
        return createStudent;
    }

    IOfAgeBornOn INamed.Named(string firstName, string lastName)
    {
        SetFirstName(student, firstName);
        SetLastName(student, lastName);
        return this;
    }

    IInSemester IOfAgeBornOn.OfAge(int age)
    {
        SetAge(student, age);
        return this;
    }

    IInSemester IOfAgeBornOn.BornOn(System.DateOnly dateOfBirth)
    {
        CallBornOn(student, dateOfBirth);
        return this;
    }

    ILivingIn IInSemester.InSemester(int semester)
    {
        SetSemester(student, semester);
        return this;
    }

    ILivingIn IInSemester.WhoStartsUniversity()
    {
        return this;
    }

    IWhoIsHappy ILivingIn.LivingIn(string? city)
    {
        SetCity(student, city);
        return this;
    }

    IWhoIsHappy ILivingIn.LivingInBoston()
    {
        return this;
    }

    IWhoIsHappy ILivingIn.InUnknownCity()
    {
        SetCity(student, null);
        return this;
    }

    IWhoseFriendsAre IWhoIsHappy.WhoIsHappy(bool? isHappy)
    {
        SetIsHappy(student, isHappy);
        return this;
    }

    IWhoseFriendsAre IWhoIsHappy.WhoIsSad()
    {
        SetIsHappy(student, false);
        return this;
    }

    IWhoseFriendsAre IWhoIsHappy.WithUnknownMood()
    {
        SetIsHappy(student, null);
        return this;
    }

    Student IWhoseFriendsAre.WhoseFriendsAre(System.Collections.Generic.IReadOnlyCollection<string> friends)
    {
        SetFriends(student, friends);
        return student;
    }

    Student IWhoseFriendsAre.WhoseFriendsAre(params string[] friends)
    {
        SetFriends(student, friends);
        return student;
    }

    Student IWhoseFriendsAre.WhoseFriendIs(string friend)
    {
        SetFriends(student, new string[1]{ friend });
        return student;
    }

    Student IWhoseFriendsAre.WhoHasNoFriends()
    {
        SetFriends(student, new string[0]);
        return student;
    }

    public interface ICreateStudent : INamed
    {
    }

    public interface INamed
    {
        IOfAgeBornOn Named(string firstName, string lastName);
    }

    public interface IOfAgeBornOn
    {
        IInSemester OfAge(int age);

        IInSemester BornOn(System.DateOnly dateOfBirth);
    }

    public interface IInSemester
    {
        ILivingIn InSemester(int semester);

        ILivingIn WhoStartsUniversity();
    }

    public interface ILivingIn
    {
        IWhoIsHappy LivingIn(string? city);

        IWhoIsHappy LivingInBoston();

        IWhoIsHappy InUnknownCity();
    }

    public interface IWhoIsHappy
    {
        IWhoseFriendsAre WhoIsHappy(bool? isHappy = true);

        IWhoseFriendsAre WhoIsSad();

        IWhoseFriendsAre WithUnknownMood();
    }

    public interface IWhoseFriendsAre
    {
        Student WhoseFriendsAre(System.Collections.Generic.IReadOnlyCollection<string> friends);

        Student WhoseFriendsAre(params string[] friends);

        Student WhoseFriendIs(string friend);

        Student WhoHasNoFriends();
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_FirstName")]
    private static extern void SetFirstName(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_LastName")]
    private static extern void SetLastName(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Age")]
    private static extern void SetAge(Student student, int value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "BornOn")]
    private static extern void CallBornOn(Student student, System.DateOnly dateOfBirth);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Semester")]
    private static extern void SetSemester(Student student, int value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_City")]
    private static extern void SetCity(Student student, string? value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_IsHappy")]
    private static extern void SetIsHappy(Student student, bool? value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Friends")]
    private static extern void SetFriends(Student student, System.Collections.Generic.IReadOnlyCollection<string> value);
}