// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using M31.FluentApi.Attributes;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.InheritedClass;

public class CreatePerson :
    CreatePerson.ICreatePerson,
    CreatePerson.IWithName,
    CreatePerson.IBornOn
{
    private readonly Person person;

    private CreatePerson()
    {
        person = new Person();
    }

    public static ICreatePerson InitialStep()
    {
        return new CreatePerson();
    }

    public static IBornOn WithName(string name)
    {
        CreatePerson createPerson = new CreatePerson();
        createPerson.person.Name = name;
        return createPerson;
    }

    IBornOn IWithName.WithName(string name)
    {
        person.Name = name;
        return this;
    }

    Person IBornOn.BornOn(System.DateOnly dateOfBirth)
    {
        person.DateOfBirth = dateOfBirth;
        return person;
    }

    public interface ICreatePerson : IWithName
    {
    }

    public interface IWithName
    {
        IBornOn WithName(string name);
    }

    public interface IBornOn
    {
        Person BornOn(System.DateOnly dateOfBirth);
    }
}