// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using M31.FluentApi.Attributes;
using SomeOtherNamespace;
using System;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentLambdaClassInDifferentNamespace;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName,
    CreateStudent.IWithAddress
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithAddress WithName(string name)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Name = name;
        return createStudent;
    }

    IWithAddress IWithName.WithName(string name)
    {
        student.Name = name;
        return this;
    }

    Student IWithAddress.WithAddress(SomeOtherNamespace.Address address)
    {
        student.Address = address;
        return student;
    }

    Student IWithAddress.WithAddress(Func<SomeOtherNamespace.CreateAddress.ICreateAddress, SomeOtherNamespace.Address> createAddress)
    {
        student.Address = createAddress(SomeOtherNamespace.CreateAddress.InitialStep());
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        IWithAddress WithName(string name);
    }

    public interface IWithAddress
    {
        Student WithAddress(SomeOtherNamespace.Address address);

        Student WithAddress(Func<SomeOtherNamespace.CreateAddress.ICreateAddress, SomeOtherNamespace.Address> createAddress);
    }
}