// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;
using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.PrivateFluentMethodNullableParameterClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName,
    CreateStudent.IBornOn,
    CreateStudent.IInSemester
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IBornOn WithName(string? name)
    {
        CreateStudent createStudent = new CreateStudent();
        CallWithName(createStudent.student, name);
        return createStudent;
    }

    IBornOn IWithName.WithName(string? name)
    {
        CallWithName(student, name);
        return this;
    }

    IInSemester IBornOn.BornOn(System.DateOnly? date)
    {
        CallBornOn(student, date);
        return this;
    }

    Student IInSemester.InSemester(int? semester)
    {
        CallInSemester(student, semester);
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        IBornOn WithName(string? name);
    }

    public interface IBornOn
    {
        IInSemester BornOn(System.DateOnly? date);
    }

    public interface IInSemester
    {
        Student InSemester(int? semester);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "WithName")]
    private static extern void CallWithName(Student student, string? name);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "BornOn")]
    private static extern void CallBornOn(Student student, System.DateOnly? date);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "InSemester")]
    private static extern void CallInSemester(Student student, int? semester);
}