// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.ContinueWithAfterCompoundClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName,
    CreateStudent.IWithProperty1,
    CreateStudent.IWithProperty2
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithProperty2 WithName(string firstName, string lastName)
    {
        CreateStudent createStudent = new CreateStudent();
        SetFirstName(createStudent.student, firstName);
        SetLastName(createStudent.student, lastName);
        return createStudent;
    }

    IWithProperty2 IWithName.WithName(string firstName, string lastName)
    {
        SetFirstName(student, firstName);
        SetLastName(student, lastName);
        return this;
    }

    IWithProperty2 IWithProperty1.WithProperty1(string property1)
    {
        SetProperty1(student, property1);
        return this;
    }

    Student IWithProperty2.WithProperty2(string property2)
    {
        SetProperty2(student, property2);
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        IWithProperty2 WithName(string firstName, string lastName);
    }

    public interface IWithProperty1
    {
        IWithProperty2 WithProperty1(string property1);
    }

    public interface IWithProperty2
    {
        Student WithProperty2(string property2);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_FirstName")]
    private static extern void SetFirstName(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_LastName")]
    private static extern void SetLastName(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Property1")]
    private static extern void SetProperty1(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Property2")]
    private static extern void SetProperty2(Student student, string value);
}