// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#nullable enable

using M31.FluentApi.Attributes;
using System.Reflection;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentNullableNoNullableAnnotationPrivateSetClass;

public class CreateStudent
{
    private readonly Student student;
    private static readonly PropertyInfo namePropertyInfo;

    static CreateStudent()
    {
        namePropertyInfo = typeof(Student).GetProperty("Name", BindingFlags.Instance | BindingFlags.Public)!;
    }

    private CreateStudent()
    {
        student = new Student();
    }

    public static Student WithName(string name)
    {
        CreateStudent createStudent = new CreateStudent();
        namePropertyInfo.SetValue(createStudent.student, name);
        return createStudent.student;
    }

    public static Student WhoseNameIsUnknown()
    {
        CreateStudent createStudent = new CreateStudent();
        namePropertyInfo.SetValue(createStudent.student, null);
        return createStudent.student;
    }
}