// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentNullableNoNullableAnnotationPrivateSetClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithName
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static Student WithName(string name)
    {
        CreateStudent createStudent = new CreateStudent();
        SetName(createStudent.student, name);
        return createStudent.student;
    }

    public static Student WhoseNameIsUnknown()
    {
        CreateStudent createStudent = new CreateStudent();
        SetName(createStudent.student, null);
        return createStudent.student;
    }

    Student IWithName.WithName(string name)
    {
        SetName(student, name);
        return student;
    }

    Student IWithName.WhoseNameIsUnknown()
    {
        SetName(student, null);
        return student;
    }

    public interface ICreateStudent : IWithName
    {
    }

    public interface IWithName
    {
        Student WithName(string name);

        Student WhoseNameIsUnknown();
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    private static extern void SetName(Student student, string value);
}