// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.ContinueWithOfOverloadedMethodClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IMethod1Method1,
    CreateStudent.IWithProperty1,
    CreateStudent.IWithProperty2
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithProperty1 Method1()
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Method1();
        return createStudent;
    }

    public static IWithProperty2 Method1(int p1)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Method1(p1);
        return createStudent;
    }

    IWithProperty1 IMethod1Method1.Method1()
    {
        student.Method1();
        return this;
    }

    IWithProperty2 IMethod1Method1.Method1(int p1)
    {
        student.Method1(p1);
        return this;
    }

    IWithProperty2 IWithProperty1.WithProperty1(string property1)
    {
        SetProperty1(student, property1);
        return this;
    }

    Student IWithProperty2.WithProperty2(string property2)
    {
        SetProperty2(student, property2);
        return student;
    }

    public interface ICreateStudent : IMethod1Method1
    {
    }

    public interface IMethod1Method1
    {
        IWithProperty1 Method1();

        IWithProperty2 Method1(int p1);
    }

    public interface IWithProperty1
    {
        IWithProperty2 WithProperty1(string property1);
    }

    public interface IWithProperty2
    {
        Student WithProperty2(string property2);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Property1")]
    private static extern void SetProperty1(Student student, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Property2")]
    private static extern void SetProperty2(Student student, string value);
}