// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using M31.FluentApi.Attributes;
using System.Reflection;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.ContinueWithOfOverloadedMethodClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IMethod1Method1,
    CreateStudent.IWithProperty1,
    CreateStudent.IWithProperty2
{
    private readonly Student student;
    private static readonly PropertyInfo property1PropertyInfo;
    private static readonly PropertyInfo property2PropertyInfo;

    static CreateStudent()
    {
        property1PropertyInfo = typeof(Student).GetProperty("Property1", BindingFlags.Instance | BindingFlags.Public)!;
        property2PropertyInfo = typeof(Student).GetProperty("Property2", BindingFlags.Instance | BindingFlags.Public)!;
    }

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithProperty1 Method1()
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Method1();
        return createStudent;
    }

    IWithProperty1 IMethod1Method1.Method1()
    {
        student.Method1();
        return this;
    }

    public static IWithProperty2 Method1(int p1)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.Method1(p1);
        return createStudent;
    }

    IWithProperty2 IMethod1Method1.Method1(int p1)
    {
        student.Method1(p1);
        return this;
    }

    IWithProperty2 IWithProperty1.WithProperty1(string property1)
    {
        property1PropertyInfo.SetValue(student, property1);
        return this;
    }

    Student IWithProperty2.WithProperty2(string property2)
    {
        property2PropertyInfo.SetValue(student, property2);
        return student;
    }

    public interface ICreateStudent : IMethod1Method1
    {
    }

    public interface IMethod1Method1
    {
        IWithProperty1 Method1();

        IWithProperty2 Method1(int p1);
    }

    public interface IWithProperty1
    {
        IWithProperty2 WithProperty1(string property1);
    }

    public interface IWithProperty2
    {
        Student WithProperty2(string property2);
    }
}