// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentMethodDefaultValuesClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IWithFirstName,
    CreateStudent.IWithLastName,
    CreateStudent.IBornOn,
    CreateStudent.IEnrolledIn,
    CreateStudent.IInSemester,
    CreateStudent.IWithNumberOfPassedExams,
    CreateStudent.IWithNumberOfFailedExams
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithLastName WithFirstName(string firstName = "Alice")
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.WithFirstName(firstName);
        return createStudent;
    }

    IWithLastName IWithFirstName.WithFirstName(string firstName)
    {
        student.WithFirstName(firstName);
        return this;
    }

    IBornOn IWithLastName.WithLastName(string? lastName)
    {
        student.WithLastName(lastName);
        return this;
    }

    IEnrolledIn IBornOn.BornOn(System.DateOnly date)
    {
        student.BornOn(date);
        return this;
    }

    IInSemester IEnrolledIn.EnrolledIn(System.DateOnly date)
    {
        student.EnrolledIn(date);
        return this;
    }

    IWithNumberOfPassedExams IInSemester.InSemester(int semester)
    {
        student.InSemester(semester);
        return this;
    }

    IWithNumberOfFailedExams IWithNumberOfPassedExams.WithNumberOfPassedExams(int? numberOfPassedExams)
    {
        student.WithNumberOfPassedExams(numberOfPassedExams);
        return this;
    }

    Student IWithNumberOfFailedExams.WithNumberOfFailedExams(int? numberOfFailedExams)
    {
        student.WithNumberOfFailedExams(numberOfFailedExams);
        return student;
    }

    public interface ICreateStudent : IWithFirstName
    {
    }

    public interface IWithFirstName
    {
        IWithLastName WithFirstName(string firstName = "Alice");
    }

    public interface IWithLastName
    {
        IBornOn WithLastName(string? lastName = null);
    }

    public interface IBornOn
    {
        IEnrolledIn BornOn(System.DateOnly date = default);
    }

    public interface IEnrolledIn
    {
        IInSemester EnrolledIn(System.DateOnly date = default);
    }

    public interface IInSemester
    {
        IWithNumberOfPassedExams InSemester(int semester = 3);
    }

    public interface IWithNumberOfPassedExams
    {
        IWithNumberOfFailedExams WithNumberOfPassedExams(int? numberOfPassedExams = default);
    }

    public interface IWithNumberOfFailedExams
    {
        Student WithNumberOfFailedExams(int? numberOfFailedExams = default);
    }
}