// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Collections.Generic;
using System;
using System.Reflection;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentReturnSingleStepPrivateMethodsClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter
{
    private readonly Student student;
    private static readonly MethodInfo returnVoidMethodMethodInfo;
    private static readonly MethodInfo returnIntMethodMethodInfo;
    private static readonly MethodInfo returnListMethodMethodInfo;
    private static readonly MethodInfo returnIntMethodWithRefParameterMethodInfo;

    static CreateStudent()
    {
        returnVoidMethodMethodInfo = typeof(Student).GetMethod(
            "ReturnVoidMethod",
            0,
            BindingFlags.Instance | BindingFlags.NonPublic,
            null,
            new Type[] {  },
            null)!;
        returnIntMethodMethodInfo = typeof(Student).GetMethod(
            "ReturnIntMethod",
            0,
            BindingFlags.Instance | BindingFlags.NonPublic,
            null,
            new Type[] {  },
            null)!;
        returnListMethodMethodInfo = typeof(Student).GetMethod(
            "ReturnListMethod",
            0,
            BindingFlags.Instance | BindingFlags.NonPublic,
            null,
            new Type[] {  },
            null)!;
        returnIntMethodWithRefParameterMethodInfo = typeof(Student).GetMethod(
            "ReturnIntMethodWithRefParameter",
            0,
            BindingFlags.Instance | BindingFlags.NonPublic,
            null,
            new Type[] { typeof(string).MakeByRefType() },
            null)!;
    }

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static void ReturnVoidMethod()
    {
        CreateStudent createStudent = new CreateStudent();
        CreateStudent.returnVoidMethodMethodInfo.Invoke(createStudent.student, new object?[] {  });
    }

    public static int ReturnIntMethod()
    {
        CreateStudent createStudent = new CreateStudent();
        return (int) CreateStudent.returnIntMethodMethodInfo.Invoke(createStudent.student, new object?[] {  })!;
    }

    public static System.Collections.Generic.List<int> ReturnListMethod()
    {
        CreateStudent createStudent = new CreateStudent();
        return (System.Collections.Generic.List<int>) CreateStudent.returnListMethodMethodInfo.Invoke(createStudent.student, new object?[] {  })!;
    }

    public static int ReturnIntMethodWithRefParameter(ref string s)
    {
        CreateStudent createStudent = new CreateStudent();
        object?[] args = new object?[] { s };
        int result = (int) CreateStudent.returnIntMethodWithRefParameterMethodInfo.Invoke(createStudent.student, args)!;
        s = (string) args[0]!;
        return result;
    }

    void IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnVoidMethod()
    {
        CreateStudent.returnVoidMethodMethodInfo.Invoke(student, new object?[] {  });
    }

    int IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnIntMethod()
    {
        return (int) CreateStudent.returnIntMethodMethodInfo.Invoke(student, new object?[] {  })!;
    }

    System.Collections.Generic.List<int> IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnListMethod()
    {
        return (System.Collections.Generic.List<int>) CreateStudent.returnListMethodMethodInfo.Invoke(student, new object?[] {  })!;
    }

    int IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter.ReturnIntMethodWithRefParameter(ref string s)
    {
        object?[] args = new object?[] { s };
        int result = (int) CreateStudent.returnIntMethodWithRefParameterMethodInfo.Invoke(student, args)!;
        s = (string) args[0]!;
        return result;
    }

    public interface ICreateStudent : IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter
    {
    }

    public interface IReturnVoidMethodReturnIntMethodReturnListMethodReturnIntMethodWithRefParameter
    {
        void ReturnVoidMethod();

        int ReturnIntMethod();

        System.Collections.Generic.List<int> ReturnListMethod();

        int ReturnIntMethodWithRefParameter(ref string s);
    }
}