// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#nullable enable

using M31.FluentApi.Attributes;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.FluentMethodParameterModifiersClass;

public class CreateStudent : CreateStudent.IMethodWithRefParameter, CreateStudent.IMethodWithInParameter, CreateStudent.IMethodWithOutParameter
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static IMethodWithRefParameter MethodWithParams(params int[] numbers)
    {
        CreateStudent createStudent = new CreateStudent();
        createStudent.student.MethodWithParams(numbers);
        return createStudent;
    }

    public IMethodWithInParameter MethodWithRefParameter(ref int n1)
    {
        student.MethodWithRefParameter(ref n1);
        return this;
    }

    public IMethodWithOutParameter MethodWithInParameter(in int n2)
    {
        student.MethodWithInParameter(in n2);
        return this;
    }

    public Student MethodWithOutParameter(out int n3)
    {
        student.MethodWithOutParameter(out n3);
        return student;
    }

    public interface IMethodWithRefParameter
    {
        IMethodWithInParameter MethodWithRefParameter(ref int n1);
    }

    public interface IMethodWithInParameter
    {
        IMethodWithOutParameter MethodWithInParameter(in int n2);
    }

    public interface IMethodWithOutParameter
    {
        Student MethodWithOutParameter(out int n3);
    }
}