using System.Runtime.CompilerServices;

namespace ExampleProject;

public class Employee2
{
    public string Name { get; private set; }

    public List<Phone> Phones { get; private set; }

    public List<Job> Jobs { get; private set; }
}

// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

public class CreateEmployee2 :
    CreateEmployee2.ICreateEmployee2,
    // todo: remove other interfaces
    CreateEmployee2.ICreateEmployee2FromExisting // todo: need this.
{
    private readonly Employee2 employee;

    private CreateEmployee2()
    {
        employee = new Employee2();
    }

    // todo: need this
    private CreateEmployee2(Employee2 employee)
    {
        this.employee = employee;
    }

    public static ICreateEmployee2 InitialStep()
    {
        return new CreateEmployee2();
    }

    // todo: need this
    public static ICreateEmployee2FromExisting From(Employee2 employee)
    {
        return new CreateEmployee2(employee);
    }

    public static IWithPhones WithName(string name)
    {
        CreateEmployee2 createEmployee2 = new CreateEmployee2();
        SetName(createEmployee2.employee, name!);
        return createEmployee2;
    }

    IWithPhones IWithName.WithName(string name)
    {
        SetName(employee, name!);
        return this;
    }

    IWithJobs IWithPhones.WithPhones(System.Collections.Generic.List<ExampleProject.Phone> phones)
    {
        SetPhones(employee, phones!);
        return this;
    }

    IWithJobs IWithPhones.WithPhones(params ExampleProject.Phone[] phones)
    {
        SetPhones(employee, new List<ExampleProject.Phone>(phones)!);
        return this;
    }

    IWithJobs IWithPhones.WithPhones(params Func<ExampleProject.CreatePhone.ICreatePhone, ExampleProject.Phone>[] createPhones)
    {
        SetPhones(employee, new List<ExampleProject.Phone>(createPhones.Select(createPhone => createPhone(ExampleProject.CreatePhone.InitialStep())))!);
        return this;
    }

    IWithJobs IWithPhones.WithPhone(ExampleProject.Phone phone)
    {
        SetPhones(employee, new List<ExampleProject.Phone>(1){ phone }!);
        return this;
    }

    IWithJobs IWithPhones.WithPhone(Func<ExampleProject.CreatePhone.ICreatePhone, ExampleProject.Phone> createPhone)
    {
        SetPhones(employee, new List<ExampleProject.Phone>(1){ createPhone(ExampleProject.CreatePhone.InitialStep()) }!);
        return this;
    }

    IWithJobs IWithPhones.WithZeroPhones()
    {
        SetPhones(employee, new List<ExampleProject.Phone>(0)!);
        return this;
    }

    Employee2 IWithJobs.WithJobs(System.Collections.Generic.List<ExampleProject.Job> jobs)
    {
        SetJobs(employee, jobs!);
        return employee;
    }

    Employee2 IWithJobs.WithJobs(params ExampleProject.Job[] jobs)
    {
        SetJobs(employee, new List<ExampleProject.Job>(jobs)!);
        return employee;
    }

    Employee2 IWithJobs.WithJobs(params Func<ExampleProject.CreateJob.ICreateJob, ExampleProject.Job>[] createJobs)
    {
        SetJobs(employee, new List<ExampleProject.Job>(createJobs.Select(createJob => createJob(ExampleProject.CreateJob.InitialStep())))!);
        return employee;
    }

    Employee2 IWithJobs.WithJob(ExampleProject.Job job)
    {
        SetJobs(employee, new List<ExampleProject.Job>(1){ job }!);
        return employee;
    }

    Employee2 IWithJobs.WithJob(Func<ExampleProject.CreateJob.ICreateJob, ExampleProject.Job> createJob)
    {
        SetJobs(employee, new List<ExampleProject.Job>(1){ createJob(ExampleProject.CreateJob.InitialStep()) }!);
        return employee;
    }

    Employee2 IWithJobs.WithZeroJobs()
    {
        SetJobs(employee, new List<ExampleProject.Job>(0)!);
        return employee;
    }

    public interface ICreateEmployee2 : IWithName
    {
    }

    public interface IWithName
    {
        IWithPhones WithName(string name);
    }

    public interface IWithPhones
    {
        IWithJobs WithPhones(System.Collections.Generic.List<ExampleProject.Phone> phones);

        IWithJobs WithPhones(params ExampleProject.Phone[] phones);

        IWithJobs WithPhones(params Func<ExampleProject.CreatePhone.ICreatePhone, ExampleProject.Phone>[] createPhones);

        IWithJobs WithPhone(ExampleProject.Phone phone);

        IWithJobs WithPhone(Func<ExampleProject.CreatePhone.ICreatePhone, ExampleProject.Phone> createPhone);

        IWithJobs WithZeroPhones();
    }

    public interface IWithJobs
    {
        Employee2 WithJobs(System.Collections.Generic.List<ExampleProject.Job> jobs);

        Employee2 WithJobs(params ExampleProject.Job[] jobs);

        Employee2 WithJobs(params Func<ExampleProject.CreateJob.ICreateJob, ExampleProject.Job>[] createJobs);

        Employee2 WithJob(ExampleProject.Job job);

        Employee2 WithJob(Func<ExampleProject.CreateJob.ICreateJob, ExampleProject.Job> createJob);

        Employee2 WithZeroJobs();
    }

    // todo: need this.
    public interface ICreateEmployee2FromExisting :
        IWithName,
        IWithPhones,
        IWithJobs
    {
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    private static extern void SetName(Employee2 employee, string value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Phones")]
    private static extern void SetPhones(Employee2 employee, System.Collections.Generic.List<ExampleProject.Phone> value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Jobs")]
    private static extern void SetJobs(Employee2 employee, System.Collections.Generic.List<ExampleProject.Job> value);
}