// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.PrivateFluentMethodParameterModifiersClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IMethodWithParams,
    CreateStudent.IMethodWithRefParameter,
    CreateStudent.IMethodWithInParameter,
    CreateStudent.IMethodWithOutParameter,
    CreateStudent.IMethodWithRefInAndOutParameter
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IMethodWithRefParameter MethodWithParams(params int[] numbers)
    {
        CreateStudent createStudent = new CreateStudent();
        CallMethodWithParams(createStudent.student, numbers);
        return createStudent;
    }

    IMethodWithRefParameter IMethodWithParams.MethodWithParams(params int[] numbers)
    {
        CallMethodWithParams(student, numbers);
        return this;
    }

    IMethodWithInParameter IMethodWithRefParameter.MethodWithRefParameter(ref int n1)
    {
        CallMethodWithRefParameter(student, ref n1);
        return this;
    }

    IMethodWithOutParameter IMethodWithInParameter.MethodWithInParameter(in int n2)
    {
        CallMethodWithInParameter(student, in n2);
        return this;
    }

    IMethodWithRefInAndOutParameter IMethodWithOutParameter.MethodWithOutParameter(out int n3)
    {
        CallMethodWithOutParameter(student, out n3);
        return this;
    }

    Student IMethodWithRefInAndOutParameter.MethodWithRefInAndOutParameter(ref int n4, in int n5, out int n6)
    {
        CallMethodWithRefInAndOutParameter(student, ref n4, in n5, out n6);
        return student;
    }

    public interface ICreateStudent : IMethodWithParams
    {
    }

    public interface IMethodWithParams
    {
        IMethodWithRefParameter MethodWithParams(params int[] numbers);
    }

    public interface IMethodWithRefParameter
    {
        IMethodWithInParameter MethodWithRefParameter(ref int n1);
    }

    public interface IMethodWithInParameter
    {
        IMethodWithOutParameter MethodWithInParameter(in int n2);
    }

    public interface IMethodWithOutParameter
    {
        IMethodWithRefInAndOutParameter MethodWithOutParameter(out int n3);
    }

    public interface IMethodWithRefInAndOutParameter
    {
        Student MethodWithRefInAndOutParameter(ref int n4, in int n5, out int n6);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "MethodWithParams")]
    private static extern void CallMethodWithParams(Student student, params int[] numbers);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "MethodWithRefParameter")]
    private static extern void CallMethodWithRefParameter(Student student, ref int n1);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "MethodWithInParameter")]
    private static extern void CallMethodWithInParameter(Student student, in int n2);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "MethodWithOutParameter")]
    private static extern void CallMethodWithOutParameter(Student student, out int n3);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "MethodWithRefInAndOutParameter")]
    private static extern void CallMethodWithRefInAndOutParameter(Student student, ref int n4, in int n5, out int n6);
}