// <auto-generated/>
// This code was generated by the library M31.FluentAPI.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable

using System.Runtime.CompilerServices;

namespace M31.FluentApi.Tests.CodeGeneration.TestClasses.Abstract.SameNameMemberClass;

public class CreateStudent :
    CreateStudent.ICreateStudent,
    CreateStudent.IInSemester,
    CreateStudent.IWithName,
    CreateStudent.IWithName2
{
    private readonly Student student;

    private CreateStudent()
    {
        student = new Student();
    }

    public static ICreateStudent InitialStep()
    {
        return new CreateStudent();
    }

    public static IWithName InSemester(int semester)
    {
        CreateStudent createStudent = new CreateStudent();
        SetSemester(createStudent.student, semester!);
        return createStudent;
    }

    IWithName IInSemester.InSemester(int semester)
    {
        SetSemester(student, semester!);
        return this;
    }

    IWithName2 IWithName.WithName(char initial)
    {
        SetInitial(student, initial!);
        return this;
    }

    Student IWithName2.WithName(string lastName)
    {
        SetLastName(student, lastName!);
        return student;
    }

    public interface ICreateStudent : IInSemester
    {
    }

    public interface IInSemester
    {
        IWithName InSemester(int semester);
    }

    public interface IWithName
    {
        IWithName2 WithName(char initial);
    }

    public interface IWithName2
    {
        Student WithName(string lastName);
    }

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Semester")]
    private static extern void SetSemester(Student student, int value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Initial")]
    private static extern void SetInitial(Student student, char value);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_LastName")]
    private static extern void SetLastName(Student student, string value);
}